### ISSUE TITLE
Thanks to you, I've made my own YAD-based youtube downloader!

### ISSUE THREAD

**Issue by Botspot** [BC2A/SavUTube#2]
After seeing your project, I took the idea of a YAD-based YouTube browser and made my own.

It includes a search engine, and the ability to play videos with vlc.  
![2020-12-15-220913_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/102304904-3d9cf080-3f24-11eb-9d66-a7e3a75b88fb.png)

Let me know what you think, and I'm open to feedback!  
https://github.com/Botspot/youtubuddy

**Comment by BC2A** [comment]
No Thank You,  I'll check it out.

On 12/15/20, Botspot <notifications@github.com> wrote:
> It includes a search engine, and the ability to play videos with vlc.
>
> ![2020-12-15-220913_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/102304904-3d9cf080-3f24-11eb-9d66-a7e3a75b88fb.png)
>
> Let me know what you think, and I'm open to feedback!
> https://github.com/Botspot/youtubuddy
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BC2A/SavUTube/issues/2


-- 
Most people don't know the difference between an i7 Core, and an Apple Core.

**Comment by Botspot** [comment]
> No Thank You, I'll check it out.

"No thank you"? lol
